### ISSUE TITLE
Database icon

### ISSUE THREAD

**Issue by yalgva** [tomolimo/impacts#4]
Hello Tomolimo,

Could you add or tell me how to add database icone. It does not exist in last version

Thank you

Have a nice day
Yannick

**Comment by tomolimo** [comment]
Hello @yalgva 

This is very easy, you add the image file into the `pics` folder. 
The name of the file must be the name of the class of the objects you want to use.
For example : `Computer.png` for icons for computers, file name is case sensitive (in Linux), and image type must be PNG. Size of the image is 256x256 pixels.
When done, you may share the picture, so that everybody will be able to use it also.

Regards,
Tomolimo

**Comment by tomolimo** [comment]
I found this one 😃 
[PluginDatabasesDatabase.zip](https://github.com/tomolimo/impacts/files/3427109/PluginDatabasesDatabase.zip)

Feel free to change it and to propose another one!

**Comment by yalgva** [comment]
Thx a lot !

**Comment by yalgva** [comment]
I tried to add knowledge base icon but it does not work, maybe cause of space between knowledge and base on the icon name

![knowledge base](https://user-images.githubusercontent.com/30655170/62055744-83b4bf80-b21c-11e9-9946-6ea07bf950aa.png)

**Comment by tomolimo** [comment]
Hello @yalgva 
You should use the name of the object class name in GLPI to name the picture file.
What's the class name of the object in GLPI?
Thank you
Regards,
Tomolimo

**Comment by yalgva** [comment]
when i open the select list it appears knowledge base

**Comment by yalgva** [comment]
Where can I find the class name ?

**Comment by tomolimo** [comment]
yes, but between brackets shouldn't you have the class name?

**Comment by yalgva** [comment]
I found it, thx

https://forge.glpi-project.org/apidoc/class-CommonGLPI.html

**Comment by tomolimo** [comment]
which version of the plugin are you using?

**Comment by yalgva** [comment]
KnowbaseItem.png

**Comment by tomolimo** [comment]
ok, thank you
